version: 0.0
os: linux
files:
  - source: .
    destination: .
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: install_service_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 3600
      runas: root